//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Малахов.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDService { get; set; }
        public int IDManager { get; set; }
        public int Count { get; set; }
        public int DurationInSecond { get; set; }
        public decimal Price { get; set; }
        public string Sum
        {
            get
            {
                return $"Стоимость: {Price} руб.";
            }
        }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
        public string StatusString
        {
            get => Status ? "Одобрено" : "Не одобрено";
        }
        public byte[] Music { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Service Service { get; set; }
    }
}
